version: 2
jobs:
  build:
    docker:
        - image: koppor/texlive
    steps:
        - checkout
        - run:
            name: Build latex
            command: |
                ls -la
                latexmk -pdf main.tex 
                mkdir result || true
                mv main.pdf result/
                cd PresTeX/
                latexmk -pdf Christos_Ioannidis_Deliverable3.tex
                mv Christos_Ioannidis_Deliverable3.pdf ../result/
                ls -lah result
        - store-artifacts:
            path: result
