version: 2
jobs:
  build:
    docker:
        - image: koppor/texlive
    steps:
        - checkout
        - run:
            name: Build latex
            command: |
                ls -la
                latexmk -pdf main.tex 
                latexmk -pdf PresTeX/Christos_Ioannidis_Deliverable3.tex
                mkdir result || true
                mv main.pdf result/
                mvn PresTeX/Christos_Ioannidis_Deliverable3.pdf result/
                ls -lah result
        - store-artifacts:
            path: result
