version: 2
jobs:
  build:
    docker:
        - image: koppor/texlive
    steps:
        - checkout
        - run:
            name: Build latex
            command: |
                ls -la
                latexmk main.tex 
                mkdir result || true
                mv main.pdf result/
                ls -lah result
        - store-artifacts:
            path: result
