version: 2
jobs:
  build:
    docker:
        - image: whatever4711/latex
    steps:
        - checkout
        - run:
            name: Build latex
            command: |
                ls -la
                tlmgrinstall
                wget http://mirrors.ctan.org/macros/latex/contrib/IEEEtran/IEEEtran.cls
                latexmk main.tex 
                mkdir result || true
                mv main.pdf result/
                ls -lah result
        - store-artifacts:
            path: result
